### ISSUE TITLE
GetMyInfoAsync() -> System.Text.Json.JsonException: '<' is an invalid start of a value. 

### ISSUE THREAD

**Issue by Robertsmania** [AdrianJSClark/aydsko-iracingdata#199]
I have code that was working fine until today.  Now I'm getting an exception when I try to interact with the data API.

For example, this code sets up the credentials and tries to get my info:

```
        private static ServiceCollection _services = new ServiceCollection();
        private static IDataClient _dataClient;
...
                _services.AddIRacingDataApi();
                using var serviceProvider = _services.BuildServiceProvider();
                _dataClient = serviceProvider.GetRequiredService<IDataClient>();
                _dataClient.UseUsernameAndPassword(iRacingUserName, iRacingPassword);
                var infoResponse = await _dataClient.GetMyInfoAsync();
```
After a few moments I get an exception:
```
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Aydsko.iRacingData.DataClient.HandleUnsuccessfulResponse(HttpResponseMessage httpResponse, String content, ILogger logger) in /_/src/Aydsko.iRacingData/DataClient.cs:line 2048
   at Aydsko.iRacingData.DataClient.CreateResponseViaInfoLinkAsync[TData](Uri infoLinkUri, JsonTypeInfo`1 jsonTypeInfo, CancellationToken cancellationToken) in /_/src/Aydsko.iRacingData/DataClient.cs:line 1959
   at Aydsko.iRacingData.DataClient.GetMyInfoAsync(CancellationToken cancellationToken) in /_/src/Aydsko.iRacingData/DataClient.cs:line 347
   at RobertsmaniaiRacing.iRacingData.SetValues(Object vProxy) in C:\Users\Kris\source\repos\RobertsmaniaiRacingVAPlugin\iRacingVAPlugin\iRacingData.cs:line 49
```
I have double checked to make sure my account is authenticated against the iRacing URLS and can access the /data endpoints interactively in the browser using the same credentials my code uses.

**Comment by AdrianJSClark** [comment]
I just tried accessing my info and, after a long delay, I got the response below via my library.

It indicates that there's an issue on the iRacing side of things, where their caching provider can't talk to the back-end systems. I also tested in the browser and received the same 504 error attempting to access `https://members-ng.iracing.com/data/member/info` after authenticating.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 3dw8AW_Tdre9-kZ6Gx2RP4lh3eWyyNYP1-tGsRaJCOaGpkW4GmvJBw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

I've already lodged a comment about this over on the forums: https://forums.iracing.com/discussion/comment/515622/#Comment_515622

**Comment by AdrianJSClark** [comment]
I'll have a think later today about how to better surface this sort of error in future, because obviously the exception you got wasn't particularly helpful in diagnosing the problem.

**Comment by Robertsmania** [comment]
Okay, thank you for the prompt reply!  My next step was going to be getting the code locally and stepping into see what was going on with:
```
   at Aydsko.iRacingData.DataClient.GetMyInfoAsync(CancellationToken cancellationToken) in /_/src/Aydsko.iRacingData/DataClient.cs:line 347
```
But that's probably where I would have found the same reply you did.

I'm sure they have their best minds on the problem, right now.

**Comment by AdrianJSClark** [comment]
No worries! Nicholas says the server has been bounced on the Forum thread, so should be resolved.

Yeah, my debug process was to use a setup I've got with a custom `HttpMessageHandler` inserted that logs the content of all responses (which I use to build some unit tests). Then looked at the content.

That error message mentioning the `JsonException` and the character `<` is a dead giveaway it has been sent some HTML rather than JSON, so is likely an error message.

**Comment by Robertsmania** [comment]
Yes, working again now.  Thanks!
